# Generated by Django 5.2 on 2025-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(verbose_name='Імʼя користувача')),
                ('user_mail', models.TextField(verbose_name='Пошта користувача')),
                ('user_password', models.TextField(verbose_name='Пароль користувача')),
            ],
        ),
    ]
