# Generated by Django 5.2 on 2025-05-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_savedfaculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='chatpgt_message_history',
            field=models.TextField(default='', verbose_name='Історія повідомлень з чатботом'),
        ),
    ]
