# Generated by Django 5.2 on 2025-05-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_students_chatpgt_message_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='chatpgt_message_history',
            new_name='chatgpt_messages_history',
        ),
    ]
