# Generated by Django 5.2 on 2025-05-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_chatpgt_message_history_students_chatgpt_messages_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='chatgpt_messages_history',
            field=models.JSONField(default='', verbose_name='Історія повідомлень з чатботом'),
        ),
    ]
