# Generated by Django 5.2 on 2025-05-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_students_chatgpt_messages_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='chatgpt_messages_history',
            field=models.JSONField(verbose_name='Історія повідомлень з чатботом'),
        ),
    ]
