# Generated by Django 5.2 on 2025-04-22 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(verbose_name='Назва університету')),
                ('fakulty_name', models.CharField(verbose_name='Назва факультету')),
                ('country', models.TextField(verbose_name='Країна')),
                ('city', models.TextField(verbose_name='Місто')),
                ('mail', models.TextField(verbose_name='Пошта')),
                ('university_description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Університет',
                'verbose_name_plural': 'Університети',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Молодший бакалавр'), (1, 'Бакалавр'), (2, 'Магістр'), (3, 'Доктор філософії'), (4, 'Доктор наук')], verbose_name='Айді ступеня освіти')),
                ('duration', models.IntegerField(verbose_name='Тривалість навчання')),
                ('cost', models.FloatField(verbose_name='Ціна')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='universities.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(verbose_name='Тип зображення')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Зображення')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='universities.faculty')),
            ],
        ),
    ]
