# Generated by Django 5.2 on 2025-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Назва університету')),
                ('faculty', models.CharField(verbose_name='Назва факультету')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
        ),
    ]
