# Generated by Django 5.2 on 2025-04-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='fakulty_name',
            new_name='faculty_name',
        ),
    ]
