# Generated by Django 5.2 on 2025-05-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'verbose_name': 'Ступінь навчання', 'verbose_name_plural': 'Ступені навчання'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото університету', 'verbose_name_plural': 'Фото університетів'},
        ),
    ]
