# Generated by Django 5.2 on 2025-04-08 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Університет', 'verbose_name_plural': 'Університети'},
        ),
        migrations.RenameField(
            model_name='university',
            old_name='faculty',
            new_name='fakulty_name',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='description',
            new_name='university_description',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='name',
            new_name='university_name',
        ),
        migrations.AddField(
            model_name='university',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата створення факультету'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='dean_name',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='ПІБ декана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='mail',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Пошта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='region',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Регіон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='rektor_name',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='ПІБ ректора'),
            preserve_default=False,
        ),
    ]
