# Generated by Django 5.2 on 2025-04-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_rename_fakulty_name_faculty_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Зображення'),
        ),
    ]
