# Generated by Django 5.2 on 2025-05-02 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_degree_cost_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='semester_start',
            field=models.DateField(default=datetime.date(2025, 5, 2), verbose_name='Дата початку семестру'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.TextField(verbose_name='Назва факультету'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='university_name',
            field=models.TextField(verbose_name='Назва університету'),
        ),
    ]
