# Generated by Django 5.2 on 2025-04-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_mg'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='bc',
            field=models.BooleanField(default=False, verbose_name='Присутність бакалаврату'),
        ),
        migrations.AlterField(
            model_name='university',
            name='mg',
            field=models.BooleanField(default=False, verbose_name='Присутність магістратури'),
        ),
    ]
