# Generated by Django 5.2 on 2025-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_degree_semester_start_alter_faculty_faculty_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='duration',
            field=models.FloatField(verbose_name='Тривалість навчання'),
        ),
    ]
