# Generated by Django 5.2 on 2025-04-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_university_bc_alter_university_mg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='region',
        ),
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.TextField(default=1, verbose_name='Місто'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.TextField(default=1, verbose_name='Країна'),
            preserve_default=False,
        ),
    ]
