# Generated by Django 5.2 on 2025-04-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_remove_university_region_university_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='dean_name',
        ),
        migrations.RemoveField(
            model_name='university',
            name='rektor_name',
        ),
    ]
